class BusStopData {
  static const Map<String, List<String>> stopNames = {
    // -------------------------------------------------------------------------
    // RUTA: Saylla Huasao
    // -------------------------------------------------------------------------
    'Saylla huasao': [
      'Luis Vallejo Santoni', // 1
      'Losa 1', // 2
      'Estrella', // 3
      'Apurímac', // 4
      'Domingo Guevara', // 5
      'Gradas', // 6
      'Teléfono', // 7
      'Ramiro Prialé', // 8
      'Parque', // 9
      'Miguel Grau', // 10
      'Zarzuela', // 11
      'Ccoripata', // 12
      'Belempampa', // 13
      '21 de Mayo', // 14
      'Puente Belén', // 15
      'Puente Grau', // 16
      'Colegio Rosario', // 17
      'Humberto Luna', // 18
      'Correo', // 19
      'La Salle', // 20
      'Mercado Wanchaq', // 21
      'Manco Inca', // 22
      'Clorinda Matto', // 23
      // ...culturaRoutes inferred based on list length in original file, resuming at index 37 in orig file
      'Camionero',
      'Santa Rosa',
      'Mercadillo',
      'San Miguel',
      'Sol de Oro',
      'Enaco',
      'Cachimayo',
      'Puente',
      'Grifo',
      'Universidad Andina',
      'Teléfono',
      'Tingo',
      'Aprovite',
      'San Martín',
      'Miraflores',
      'Penal',
      'San Juan',
      'Control-corporation roca',
      'Farmacia',
      'Paradero Medio',
      'Tercer Paradero',
      'Romeritos',
      'Posta',
      'Tapia',
      'Forestal',
      'Kayra',
      'Puente Huacoto',
      'Collana',
      'U Andina',
      'Kinta',
      'Entrada',
      'Peaje',
      'Llamagas',
      'Angostura',
      'Saywas',
      'Bosque',
      'Cristal',
      'Cruce',
      'Primero',
      'Segundo',
      'Tercero',
      'Estadio',
      'Chingo',
      'Rico Pollo',
      'Tienda',
      'Huasao',
      'Salón',
      'Plaza',
      'Colegio',
      'Mariscal Gamarra',
    ],

    // -------------------------------------------------------------------------
    // RUTA: Saylla Tipon Oropesa
    // -------------------------------------------------------------------------
    'Saylla Tipon Oropesa': [
      'Puente Sipaspucyo',
      'Puente de la Almudena',
      'Puente Santiago',
      'Pera',
      'Puente Belén',
      'Puente Grau ejercito',
      'Gradas',
      'Estación',
      'La Salle(subidaLa Salle)',
      'Mercado Wanchaq',
      'Manco Inca',
      'Huayna Capac',
      'Tacna',
      'Plaza Túpac Amaru',
      'Segundo',
      'Región',
      'Seguro',
      'Espinar',
      'Coliseo',
      'Hospital Regional',
      'Manuel Prado',
      'Magisterio',
      'Marcavalle',
      'Santa Ursula',
      'Primer paradero de San Sebastián',
      'Callejón',
      'Segundo paradero de San Sebastián',
      'Tercero paradero de San Sebastián',
      'Cuarto paradero de San Sebastián',
      'Quinto paradero de San Sebastián',
      'Sexto paradero de San Sebastián',
      'Séptimo paradero de San Sebastián',
      'Camionero',
      'Santa Rosa',
      'Mercadillo',
      'San Miguel',
      'Sol de Oro',
      'Enaco',
      'Cachimayo',
      'Puente',
      'Grifo',
      'Universidad Andina',
      'Teléfono',
      'Tingo',
      'Aprovite',
      'San Martín',
      'Miraflores',
      'Penal',
      'San Juan',
      'Control-corporation roca',
      'Farmacia',
      'Paradero Medio',
      'Tercer Paradero',
      'Romeritos',
      'Posta',
      'Tapia',
      'Forestal',
      'Kayra',
      'Puente Huacoto',
      'Collana',
      'U Andina',
      'Kinta',
      'Entrada',
      'Peaje',
      'Llamagas',
      'Angostura',
      'Saywas',
      'Bosque',
      'Cristal',
      'Cruce',
      'Primero',
      'Segundo',
      'Tercero',
      'Estadio',
      'Chingo',
      'Rico Pollo',
      'Nuevo Huasao',
      'Alicorp',
      'Real Naciente Huasao',
      'Tipón',
      'Chancadora',
      'Campamento',
      'Campamento (corrección)',
      'Grifo Pecsa',
      'Comisaría de Oropesa',
      'Patacalle',
      'Perú',
      'Plaza de Oropesa',
    ],

    // -------------------------------------------------------------------------
    // RUTA: Pachacute
    // -------------------------------------------------------------------------
    'Pachacute': [
      'Límite Provincial Cusco - Anta',
      'Quinta Campestre',
      'Chicharonerías',
      'Entrada a Estadio de Poroy',
      'Poroy',
      'Entrada Ferrocarril',
      'Grifo',
      'Entrada Cementerio',
      'Action Valley',
      'Grifo Primax',
      'Huampar',
      'Asociación Kantu',
      'Paradero Pepsi',
      'Paradero Sat',
      'Arco Tica Tica',
      'Quinta Mollendinah',
      'Reservorio',
      'Huanca',
      'Huasa Huara',
      'Posta Miraflores',
      'Mercado Tica Tica',
      'Arco de Tica Tica',
      'Jayanca',
      'San Benito',
      'Villa María',
      'Mirador',
      'Desvío',
      'La Ñusta',
      'Paradero Zorro',
      'Gradas',
      'Loza',
      'San Isidro',
      'Paradero Nihuas',
      'Entrada',
      'Puente',
      'Chicago',
      'Curva',
      'Grifo Terminal',
      'Terminal de Quillabamba',
      'Almudena',
      'Los Ángeles',
      'Esquina Plaza Santiago',
      'Parque Plaza Santiago',
      'Puente Santiago',
      'Tres Cruces de Oro, 240a',
      'Belén',
      'Puente Grau paradero',
      'Colegio Rosario',
      'Humberto Luna',
      'Correo',
      'La Salle',
      'Mercado Wanchaq',
      'Manco Inca',
      'Huayna Capac',
      'Garcilaso',
      'Puerta 6',
      'Collasuyo',
      'Andenes',
      'Paradero Kiosko',
      'Paradero Aldea',
      'Manzanares',
      'Plaza Vea',
      'Restaurante',
      'Imperio',
      'Universidad Global',
      'Paradero',
      'Trilce',
      'Esquina',
      'Iquique',
      'Calle Bolívar',
      'Velasco Alvarado',
      'Albergue',
      'Rompemuelle',
      'Esquina Segundo Paradero de San Sebastián',
      '3er Paradero SS',
      '4to Paradero SS',
      '5to Paradero SS',
      '6to Paradero SSz',
      '7mo Paradero SS',
      'Camionero',
      'Santa Rosa',
      'Mercadillo',
      'San Miguel',
      'Sol de Oro',
      'Enaco',
      'Cachimayo',
      'Puente Túpac Amaru',
      'Grifo Móvil',
      'Universidad Andina',
      'Teléfono',
      'Tingo',
      'Aprovite',
      'Grifo San Martín',
      'Entrada Sucucalle',
      'Puente Huatanay',
      'Santa Elena',
      'Medio',
      'Alameda 4 de Octubres',
    ],

    // -------------------------------------------------------------------------
    // RUTA: Leon de San Jeronimo
    // -------------------------------------------------------------------------
    'Leon de San Jeronimo': [
      'Puquín - Hermanos Ayar',
      'Hermanos Ayar',
      'Tienda',
      '1 de Mayo',
      '1 de Diciembre',
      'Sol Moqueguano',
      'Curva',
      'Escaleras',
      'Esquina',
      'Chicago',
      'Curva',
      'Grifo Terminal',
      'Terminal de Quillabamba',
      'Almudena',
      '7 Mascarrones',
      'Villa del Sol',
      'Esquina Plaza Santiago',
      'Colegio Fe y Alegría',
      'Plaza Belén',
      'Puente Belén',
      'Ayacucho',
      'El Sol',
      'Pampa del Castillo',
      'Limacpampa',
      'Huáscar',
      'Tacna -Corinda Matto',
      // ...culturaRoutes gap roughly
      'Camionero',
      'Santa Rosa',
      'Mercadillo',
      'San Miguel',
      'Sol de Oro',
      'Enaco',
      'Cachimayo',
      'Puente Túpac Amaru',
      'Grifo Móvil',
      'Universidad Andina',
      'Teléfono',
      'Tingo',
      'Aprovite',
      'San Martín',
      'Miraflores',
      'Penal',
      'San Juan',
      'Control',
      'Esquina Mercado',
      'Puerta 7-Mercado Vinocanchón',
      'La Cultura',
      'Farmacia',
      'Paradero Medio',
      'Tercer Paradero',
      'Romeritos',
      'Posta',
      'Tapia',
      'Forestal',
      'Kayra',
      'Puente Huacoto',
      'Collana',
      'U Andina',
      'Kinta',
      'Entrada',
      'Peaje',
      'Llamagas',
      'Angostura',
      'Saywas',
      'Bosque',
      'Cristal',
      'Cruce',
      'Primero',
      'Segundo',
      'Tercero',
      'Estadio',
      'Chingo',
      'Rico Pollo',
      'Nuevo Huasao',
      'Alicorp',
      'Real Naciente Huasao',
      'Tipón',
      'Chancadora',
      'Campamento',
      'Campamento (corrección)',
      'Grifo Pecsa',
      'Comisaría de Oropesa',
      'Patacalle',
      'Perú',
      'Plaza de Oropesa',
    ],

    // -------------------------------------------------------------------------
    // RUTA: Cristo Blanco
    // -------------------------------------------------------------------------
    'Cristo Blanco': [
      'Luis Vallejo Santoni',
      'Losa 1',
      'Estrella',
      'Apurímac',
      'Domingo Guevara',
      'Gradas',
      'Teléfono',
      'Ramiro Prialé',
      'Parque',
      'Miguel Grau',
      'Zarzuela',
      'Ccoripata',
      'Plaza Belén',
      'Colegio Fe y Alegría',
      'Plaza Santiago',
      'Puente Santiago',
      'Tres Cruces de Oro, 240a',
      'Belén',
      'Puente Grau paradero',
      'Colegio Rosario',
      'Humberto Luna',
      'Correo',
      'La Salle',
      'Mercado Wanchaq',
      'Manco Inca',
      'Tacna',
      'Institución Educativa',
      'Grifo',
      'Plaza Zarumilla(Zarumilla)',
      'Retiro',
      'Recolecta',
      'Mercado de Rosaspata',
      'Mariscal Gamarra',
      'Occhullo',
      'Andes Perú',
      'Hotel Mirador',
      'Lorohuachana',
      'Mirador Kanka',
      'Media Luna',
      'Lucrepata',
      'Palacio del Inka',
      'Cruz de Tete Qaqa',
      'Balconcillo',
      'Mosocllacta',
      'Camino Qhapaq Ñan',
      'Entrada',
      'Mesa',
      'Chozas',
      'Señal',
      'Cristo Blanco',
      'Entrada a Sacsayhuamán',
      'Desvío',
      'Q´enqo',
      'Estacionamiento Cristo Blanco S.A.'
    ],

    // -------------------------------------------------------------------------
    // RUTA: Señor del Huerto
    // -------------------------------------------------------------------------
    'Señor del Huerto': [
      'Final Ccorimarca',
      'Entrada a Sequeracay',
      'Sequer',
      'Chitapampa',
      'APV Incaqsamanan',
      'Esquina',
      'Cruce',
      'Mercado de Productores de Corao',
      'Corao',
      'Tienda de Abarrotes',
      '1 de Marzo',
      'Entrada a Yuncaypata',
      'Tambomachay',
      'Puka Pucara',
      'Huayllarccocha',
      'Zona X',
      'Q\'enqo',
      'Desvío',
      'Entrada a Sacsayhuamán',
      'Cristo Blanco',
      'Señal',
      'Chozas',
      'Mesa',
      'Entrada',
      'Camino Qhapaq Ñan',
      'Mosocllacta',
      'Balconcillo',
      'Cruz de Tete Qaqa',
      'Palacio del Inka',
      'Lucrepata',
      'Media Luna',
      'Mirador Kanka',
      'Lorohuachana',
      'Hotel Mirador',
      'Andes Perú',
      'Occhullo',
      'Mariscal Gamarra',
      'Mercado de Rosaspata',
      'Puputi(bajda)',
      'Garcilaso',
      'Amauta',
      'Los Incas',
      'Seguro',
      'Calca',
      'Mercado de Ttito (bajada)',
      '28 de Julio(bajada)',
      'Tercer Paradero de Ttito(SUBIDA)',
      'Segundo Puente(SUBIDA)',
      'Segundo Paradero de Ttito(SUBIDA)',
      'Primer Paradero de Ttito(SUBIDA)',
      'Terminal Terrestre',
      'Avenida 28 de Julio',
      'Óvalo Pachacuteq (subida)',
      'Terminal Terrestre Wanchaq',
      'Picador',
      'Molino',
      'Manco Cápac',
      'Viva El Perú',
      'Esquina',
      'Picaflor',
      'Colegio Viva El Perú',
      'Medio',
      'Esquina',
      'Estacionamiento Señor del Huerto S.A.',
    ],

    // -------------------------------------------------------------------------
    // RUTA: Nuevo Mirador
    // -------------------------------------------------------------------------
    'Nuevo Mirador': [
      'Final Cachona',
      'Octavo',
      'Séptimo',
      'Sexto',
      'Quinto',
      'Cuarto',
      'Reservorio',
      'Segundo',
      'Primero',
      'Subida - Juan Espinoza Medrano',
      'Esquina - Carretera Comunidad Chocco',
      'Entrada',
      'Grifo',
      'Puente',
      'Salcatay',
      'Esquina',
      'Gradas',
      'Puerto',
      'Mercado De Huancaro',
      'Colegio San Jose Obreo',
      'Perú',
      'Zarzuela',
      'Ccoripata',
      'Belempampa',
      '17. Colegio Rosario',
      '18. Humberto Luna',
      'Pardo Paseo de los Héroes',
      'Estación Hotel',
      'Estación Avenida Pardo',
      'Confraternidad',
      'Cruce Andina',
      'Parque Urpicha',
      'Óvalo Pachacuteq(bajada)',
      'Entrada a Terminal',
      'Hospedaje',
      'Terminal Terrestre',
      'Primer Paradero de Ttito',
      'Segundo Paradero de Ttito',
      'Segundo Puente',
      'Tercer Paradero de Ttito',
      'Tercer Paradero (DE VIA EXPRESA)',
      'Cuarto Puente',
      'Quinto Puente',
      'Vía Expresa',
      'República de Brasil',
      'Túpac Amaru',
      'Colombia',
      'Chile',
      'Américas',
      'República de Argentina',
      'República del Perú',
      'Túpac Amaru (repetido)',
      'Cusco',
      'Primer Paradero de San Sebastián (Avenida Cusco-parte de abajo)',
      'Callejón (parte de abajo)',
      'Plaza de San Sebastián (parte de abajo)',
      'Segundo Paradero de San Sebastián (Avenida Cusco-parte de abajo)',
      'Tercer Paradero de San Sebastián (Avenida Cusco- parte de abajo)',
      'Cuarto Paradero de San Sebastián (Avenida Cusco-parte de abajo)',
      'Sexto Paradero de San Sebastián (Avenida Cusco-parte de abajo)',
      '7mo Paradero SS',
      'Camionero',
      'Santa Rosa',
      'Mercadillo',
      'San Miguel',
      'Sol de Oro',
      'Enaco',
      'Cachimayo',
      'Puente Túpac Amaru',
      'Grifo Móvil',
      'Universidad Andina',
      'Teléfono',
      'Tingo',
      'Aprovite',
      'Grifo San Martín',
      'Kantu Versalles',
      'Ciro Alegría',
      'Petroperú',
      'Penal Esquina',
      'San Juan',
      'Control',
      'Esquina Mercado',
      'Puerta 7-Mercado Vinocanchón',
      'Agustín Gamarra',
      'Velasco Astete',
      'Santa Rosa',
      'Sorama',
      'Almagro',
      'Romeritos',
      'Licorería',
      'Grifo',
      'Estadio',
      'Kayra',
      'Puente Huacoto',
      'Collana',
      'U Andina',
      'Kinta',
      'Entrada',
      'Peaje',
      'Llamagas',
      'Angostura',
      'Saywas',
      'Bosque',
      'Cristal',
      'Cruce',
      'Primero',
      'Segundo',
      'Tercero',
      'Estadio',
      'Estadio de Saylla (Final del Mirador)',
    ],
  };
}
